### ISSUE TITLE
Download plot table not working for histograms

### ISSUE THREAD

**Issue by wfulp** [CRI-iAtlas/iatlas.modules#70]
Thanks for this amazing app. I noticed the "Download plot table" button does not work for histograms. I get a "Failed - server problems" error. All the other plot tables download as expected (violin plots, scatter plots, heatmaps, ...), and I see this error the following CG modules:Immune Feature Trends, Immunomodulators, and IO Targets. I get this issue on Chrome and Safari.

I believe the issue is related to this iatlas.modules package, but if this is not the case let me know and I can move the issue.

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/12237512/203132064-7e45b771-465c-46f1-b114-437f6e7f86db.png">

**Comment by heimannch** [comment]
Thanks for the report @wfulp! The issue has been fixed, and it will be propagated to the iAtlas app in our next release.
